Assignment 2 : Numpy and Pandas Basics

Importing Pandas and Numby Library 

In [13]:
import numpy as np  #importing numpy
import pandas as pd  #importing pandas

Numby Basics

Task 1 : Creating arrays in numpy

In [14]:
arr_1d = np.array([1, 2, 3, 4, 5]) #Create a 1D Numpy array
print("1D Array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) #Creating a 2D Numpy array
print("2D Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


Task 2 : Basic arithmetic operations on the arrays

In [15]:
arr_1d_add = arr_1d + 10    #Adding 10 to each element of the array
arr_2d_mult = arr_2d * 2    #Multiplying each element of the array by 2 
print("1D Array + 10:", arr_1d_add)
print("2D Array * 2:\n", arr_2d_mult)

1D Array + 10: [11 12 13 14 15]
2D Array * 2:
 [[ 2  4  6]
 [ 8 10 12]]


Task 3 : Indexin and Slicking on arrays

In [17]:
print("First element of 1D array:", arr_1d[0])  #Using indexing to access the first element of array
print("First row of 2D array:\n", arr_2d[0, :])     #Using slicking to access the first first row of the array

First element of 1D array: 1
First row of 2D array:
 [1 2 3]


Task 4 : Checking the shape of array and reshaping an array

In [4]:
print("Shape of 2D array:", arr_2d.shape)   #checking the shape of 2D array
reshaped_arr = arr_2d.reshape((3, 2))       #reshaping the 2d array into a new array with 3 rows and 2 columns
print("Reshaped 2D Array:\n", reshaped_arr)

Shape of 2D array: (2, 3)
Reshaped 2D Array:
 [[1 2]
 [3 4]
 [5 6]]


Pandas Basics

Task 1 : Series and DataFrame Creation

In [19]:
s = pd.Series([1, 2, 3, 4, 5])  #Creating a Pandas Series
print("Pandas Series:\n", s)

df = pd.DataFrame({     #Creating a Pandas DataFrame with 3 columns
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})
print("Pandas DataFrame:\n", df)

Pandas Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
Pandas DataFrame:
    A  B  C
0  1  4  7
1  2  5  8
2  3  6  9


Task 2 : Reading Data from CSV File

In [20]:
df_read = pd.read_csv('sample_data.csv')    #Reading data from a CSV file into a Pandas DataFrame.
print("Read DataFrame from CSV:\n", df_read)

Read DataFrame from CSV:
    A  B  C
0  1  4  7
1  2  5  8
2  3  6  9


Task 3 : Data Inspection

In [22]:
print("Head of DataFrame:\n", df.head())    #Displaying the first few rows of the DataFrame.
print("Info of DataFrame:\n", df.info())    #Displaying information about the DataFrame
print("Description of DataFrame:\n", df.describe())     #Providing summary statistics for columns in the DataFrame.

Head of DataFrame:
    A  B  C
0  1  4  7
1  2  5  8
2  3  6  9
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes
Info of DataFrame:
 None
Description of DataFrame:
          A    B    C
count  3.0  3.0  3.0
mean   2.0  5.0  8.0
std    1.0  1.0  1.0
min    1.0  4.0  7.0
25%    1.5  4.5  7.5
50%    2.0  5.0  8.0
75%    2.5  5.5  8.5
max    3.0  6.0  9.0


Task 4 : Data Manipulation

In [23]:
print("Column A\n", df['A'])                    # Selecting column A from the DataFrame
print("Columns A and B:\n", df[['A', 'B']])     # Selecting columns A and B from the DataFrame


Column A
 0    1
1    2
2    3
Name: A, dtype: int64
Columns A and B:
    A  B
0  1  4
1  2  5
2  3  6


Task 5 : Filtering Data from DataFrame

In [24]:
filtered_df = df[df['A'] > 1]                             #Filtering the DataFrame to include only rows where column A is greater than 1.
print("Filtered DataFrame (A > 1):\n", filtered_df)

Filtered DataFrame (A > 1):
    A  B  C
1  2  5  8
2  3  6  9


Adding/Removing Columns from DataFrame

In [10]:
df['D'] = df['A'] + df['B']                         #Adding a new column D which is the sum of columns A and B
print("DataFrame with new column D:\n", df)
df.drop('D', axis=1, inplace=True)                  #Droping column D from the DataFrame
print("DataFrame after dropping column D:\n", df)

DataFrame with new column D:
    A  B  C  D
0  1  4  7  5
1  2  5  8  7
2  3  6  9  9
DataFrame after dropping column D:
    A  B  C
0  1  4  7
1  2  5  8
2  3  6  9


Handling Missing Data

In [11]:
df_with_nan = df.copy()                     #Creatingg a copy of the DataFrame df.
df_with_nan.loc[1, 'B'] = np.nan            #Accessing the element located at index 1 and column B.
print("DataFrame with NaN:\n", df_with_nan)
print("DataFrame after dropping NaN:\n", df_with_nan.dropna())
print("DataFrame after filling NaN with 0:\n", df_with_nan.fillna(0))

DataFrame with NaN:
    A    B  C
0  1  4.0  7
1  2  NaN  8
2  3  6.0  9
DataFrame after dropping NaN:
    A    B  C
0  1  4.0  7
2  3  6.0  9
DataFrame after filling NaN with 0:
    A    B  C
0  1  4.0  7
1  2  0.0  8
2  3  6.0  9


Task 3: Data Analysis with Pandas

Aggregations in Pandas

In [25]:
print("Mean of column A:", df['A'].mean())      #Calculating the mean of column A.
print("Sum of column A:", df['A'].sum())        #Calculateing the sum of column A.

Mean of column A: 2.0
Sum of column A: 6


Merging and Joining

In [26]:
df1 = pd.DataFrame({'key': ['A', 'B', 'C'], 'value': [1, 2, 3]})
df2 = pd.DataFrame({'key': ['A', 'B', 'D'], 'value': [4, 5, 6]})
merged_df = pd.merge(df1, df2, on='key', how='inner')           #Mergeing the two DataFrames on the 'key' column, keeping only the rows where the 'key' is present in both
print("Merged DataFrame:\n", merged_df)



Merged DataFrame:
   key  value_x  value_y
0   A        1        4
1   B        2        5


Pivot Tables

In [27]:
pivot_df = df.pivot_table(values='C', index='A', columns='B', aggfunc='mean')       #Creating a pivot table with values from column C, indexed by column A and columns by column B, using the mean as the aggregation function.

print("Pivot Table:\n", pivot_df)



Pivot Table:
 B    4    5    6
A               
1  7.0  NaN  NaN
2  NaN  8.0  NaN
3  NaN  NaN  9.0


Time Series Analysis

In [32]:
df['date'] = pd.date_range(start='1/1/2020', periods=len(df), freq='D')     #Creatingg a date range starting from January 1, 2020
print("DataFrame with Date Index:\n", df)                                   #Setting the 'date' column as the index of the DataFrame
resampled_df = df.resample('M').mean()                                      #Resampling the DataFrame by month and calculating the mean for each month.
print("Resampled DataFrame:\n", resampled_df)                               

DataFrame with Date Index:
             A  B  C       date
date                          
2020-01-01  1  4  7 2020-01-01
2020-01-02  2  5  8 2020-01-02
2020-01-03  3  6  9 2020-01-03
Resampled DataFrame:
               A    B    C       date
date                                
2020-01-31  2.0  5.0  8.0 2020-01-02


C:\Users\Atankabadi\AppData\Local\Temp\ipykernel_16376\3617418735.py:3: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  resampled_df = df.resample('M').mean()                                      #Resampling the DataFrame by month and calculating the mean for each month.
